name: Android CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up Java 17
        uses: actions/setup-java@v1
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Prepare local properties file
        run: |
          echo "zenid_url=https://abc" >> local.properties  \
          echo "zenid_apikey=abc" >> local.properties

      - name: Build with Gradle
        env:
          USERNAME: ${{ secrets.CAMERAVIEW_MAVEN_USERNAME }}
          TOKEN: ${{ secrets.CAMERAVIEW_MAVEN_PASSWORD }}
        run: ./gradlew basic-sample:clean build
